import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased max-h-[100vh] bg-gray-200`}
      >
        <div className="container flex flex-col items-center justify-center mx-auto p-2 md:p-0">
        <Header/>
        {children}
        </div>
      </body>
    </html>
  //   <html lang="en">
  //   <body
  //     className={`${geistSans.variable} ${geistMono.variable} antialiased max-h-[100vh]`}
  //   >
  //     {children}
  //   </body>
  // </html>
  );
}
